package com.tctvn.entity;
// Generated Jul 14, 2016 8:55:16 AM by Hibernate Tools 4.3.4.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.tctvn.utils.InterfaceEnum;

/**
 * Staff generated by hbm2java
 */
@Entity
@Table(name = "staff", catalog = "springmvc")
public class Staff implements java.io.Serializable {

    public static enum GENDER implements InterfaceEnum {
        MALE(0, "Male"),
        FEMALE(1, "Female");
        private final Integer value;
        private final String label;
        GENDER(Integer value, String label) {
            this.value = value;
            this.label = label;
        }
        @Override
        public Integer getValue() {
            return value;
        }
        public String getLabel() {
            return label;
        }
    }
    
    public enum POSITION implements InterfaceEnum{
        JE(0, "Junior Engineer"),
        ME(1, "Middle Engineer"),
        SE(2, "Senior Engineer"),
        TL(3, "Team Leader"),
        PM(4, "Project Manager"),
        ;
        
        private final Integer value;
        private final String label;
        POSITION(Integer value, String label) {
            this.value = value;
            this.label = label;
        }
        @Override
        public Integer getValue() {
            return value;
        }
        public String getLabel() {
            return label;
        }
    }
    
    private Integer id;
    private String name;
    private String kananame;
    private Date birthday;
    private String email;
    private Integer gender;
    private String mobile;
    private Integer position;

    public Staff() {
    }

    public Staff(String name, String kananame, Date birthday, String email, Integer gender, String mobile, Integer position) {
        this.name = name;
        this.kananame = kananame;
        this.birthday = birthday;
        this.email = email;
        this.gender = gender;
        this.mobile = mobile;
        this.position = position;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "name", length = 45)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "kananame", length = 45)
    public String getKananame() {
        return this.kananame;
    }

    public void setKananame(String kananame) {
        this.kananame = kananame;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "birthday", length = 10)
    public Date getBirthday() {
        return this.birthday;
    }

    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    @Column(name = "email", length = 45)
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Column(name = "gender")
    public Integer getGender() {
        return this.gender;
    }

    public void setGender(Integer gender) {
        this.gender = gender;
    }

    @Column(name = "mobile", length = 15)
    public String getMobile() {
        return this.mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    @Column(name = "position")
    public Integer getPosition() {
        return position;
    }

    public void setPosition(Integer position) {
        this.position = position;
    }
}
