package com.tctvn.entity;
// Generated Jul 14, 2016 8:55:16 AM by Hibernate Tools 4.3.4.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * UserRoles generated by hbm2java
 */
@Entity
@Table(name = "user_roles", catalog = "springmvc", uniqueConstraints = @UniqueConstraint(columnNames = { "USERNAME", "USER_ROLE" }))
public class UserRoles implements java.io.Serializable {

    private String roleId;
    private String username;
    private String userRole;

    public UserRoles() {
    }

    public UserRoles(String roleId, String username, String userRole) {
        this.roleId = roleId;
        this.username = username;
        this.userRole = userRole;
    }

    @Id

    @Column(name = "ROLE_ID", unique = true, nullable = false, length = 50)
    public String getRoleId() {
        return this.roleId;
    }

    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }

    @Column(name = "USERNAME", nullable = false, length = 36)
    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    @Column(name = "USER_ROLE", nullable = false, length = 30)
    public String getUserRole() {
        return this.userRole;
    }

    public void setUserRole(String userRole) {
        this.userRole = userRole;
    }

}
