package com.tctvn.entity;
// Generated Jul 14, 2016 8:55:16 AM by Hibernate Tools 4.3.4.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "users", catalog = "springmvc")
public class Users implements java.io.Serializable {

    private String username;
    private String password;
    private short enabled;

    public Users() {
    }

    public Users(String username, String password, short enabled) {
        this.username = username;
        this.password = password;
        this.enabled = enabled;
    }

    @Id

    @Column(name = "USERNAME", unique = true, nullable = false, length = 36)
    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    @Column(name = "PASSWORD", nullable = false, length = 36)
    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    @Column(name = "ENABLED", nullable = false)
    public short getEnabled() {
        return this.enabled;
    }

    public void setEnabled(short enabled) {
        this.enabled = enabled;
    }

}
